//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace threadUTau.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string changePassword(string currentPassword, string newPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<string> changePasswordAsync(string currentPassword, string newPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_sp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable insertTable_sp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_sp", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> insertTable_spAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_ev", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable insertTable_ev();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_ev", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> insertTable_evAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_tr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable insertTable_tr();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_tr", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> insertTable_trAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_un", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable insertTable_un();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_un", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> insertTable_unAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_sp_comm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable insertTable_sp_comm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_sp_comm", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> insertTable_sp_commAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_ev_comm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable insertTable_ev_comm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_ev_comm", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> insertTable_ev_commAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_tr_comm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable insertTable_tr_comm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_tr_comm", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> insertTable_tr_commAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_un_comm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable insertTable_un_comm(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertTable_un_comm", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> insertTable_un_commAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/register", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool register(string email, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/register", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> registerAsync(string email, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> loginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool postMessage(string CurrentThread, string post, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> postMessageAsync(string CurrentThread, string post, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deleteMessage(string CurrentThread, int id, string username_table, string username_label);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteMessageAsync(string CurrentThread, int id, string username_table, string username_label);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool postComment(string CurrentThread, int id, string comm, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postComment", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> postCommentAsync(string CurrentThread, int id, string comm, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deleteComment(string CurrentThread, int id, string comment, string username_table, string username_label);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteComment", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteCommentAsync(string CurrentThread, int id, string comment, string username_table, string username_label);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPassMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SendPassMail(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPassMail", ReplyAction="*")]
        System.Threading.Tasks.Task SendPassMailAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : threadUTau.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<threadUTau.ServiceReference1.WebService1Soap>, threadUTau.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string changePassword(string currentPassword, string newPassword, string username) {
            return base.Channel.changePassword(currentPassword, newPassword, username);
        }
        
        public System.Threading.Tasks.Task<string> changePasswordAsync(string currentPassword, string newPassword, string username) {
            return base.Channel.changePasswordAsync(currentPassword, newPassword, username);
        }
        
        public System.Data.DataTable insertTable_sp() {
            return base.Channel.insertTable_sp();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> insertTable_spAsync() {
            return base.Channel.insertTable_spAsync();
        }
        
        public System.Data.DataTable insertTable_ev() {
            return base.Channel.insertTable_ev();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> insertTable_evAsync() {
            return base.Channel.insertTable_evAsync();
        }
        
        public System.Data.DataTable insertTable_tr() {
            return base.Channel.insertTable_tr();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> insertTable_trAsync() {
            return base.Channel.insertTable_trAsync();
        }
        
        public System.Data.DataTable insertTable_un() {
            return base.Channel.insertTable_un();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> insertTable_unAsync() {
            return base.Channel.insertTable_unAsync();
        }
        
        public System.Data.DataTable insertTable_sp_comm(int id) {
            return base.Channel.insertTable_sp_comm(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> insertTable_sp_commAsync(int id) {
            return base.Channel.insertTable_sp_commAsync(id);
        }
        
        public System.Data.DataTable insertTable_ev_comm(int id) {
            return base.Channel.insertTable_ev_comm(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> insertTable_ev_commAsync(int id) {
            return base.Channel.insertTable_ev_commAsync(id);
        }
        
        public System.Data.DataTable insertTable_tr_comm(int id) {
            return base.Channel.insertTable_tr_comm(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> insertTable_tr_commAsync(int id) {
            return base.Channel.insertTable_tr_commAsync(id);
        }
        
        public System.Data.DataTable insertTable_un_comm(int id) {
            return base.Channel.insertTable_un_comm(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> insertTable_un_commAsync(int id) {
            return base.Channel.insertTable_un_commAsync(id);
        }
        
        public bool register(string email, string username, string password) {
            return base.Channel.register(email, username, password);
        }
        
        public System.Threading.Tasks.Task<bool> registerAsync(string email, string username, string password) {
            return base.Channel.registerAsync(email, username, password);
        }
        
        public bool login(string username, string password) {
            return base.Channel.login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> loginAsync(string username, string password) {
            return base.Channel.loginAsync(username, password);
        }
        
        public bool postMessage(string CurrentThread, string post, string username) {
            return base.Channel.postMessage(CurrentThread, post, username);
        }
        
        public System.Threading.Tasks.Task<bool> postMessageAsync(string CurrentThread, string post, string username) {
            return base.Channel.postMessageAsync(CurrentThread, post, username);
        }
        
        public bool deleteMessage(string CurrentThread, int id, string username_table, string username_label) {
            return base.Channel.deleteMessage(CurrentThread, id, username_table, username_label);
        }
        
        public System.Threading.Tasks.Task<bool> deleteMessageAsync(string CurrentThread, int id, string username_table, string username_label) {
            return base.Channel.deleteMessageAsync(CurrentThread, id, username_table, username_label);
        }
        
        public bool postComment(string CurrentThread, int id, string comm, string username) {
            return base.Channel.postComment(CurrentThread, id, comm, username);
        }
        
        public System.Threading.Tasks.Task<bool> postCommentAsync(string CurrentThread, int id, string comm, string username) {
            return base.Channel.postCommentAsync(CurrentThread, id, comm, username);
        }
        
        public bool deleteComment(string CurrentThread, int id, string comment, string username_table, string username_label) {
            return base.Channel.deleteComment(CurrentThread, id, comment, username_table, username_label);
        }
        
        public System.Threading.Tasks.Task<bool> deleteCommentAsync(string CurrentThread, int id, string comment, string username_table, string username_label) {
            return base.Channel.deleteCommentAsync(CurrentThread, id, comment, username_table, username_label);
        }
        
        public void SendPassMail(string username) {
            base.Channel.SendPassMail(username);
        }
        
        public System.Threading.Tasks.Task SendPassMailAsync(string username) {
            return base.Channel.SendPassMailAsync(username);
        }
    }
}
